version: '4.14'

services:
  django_gunicorn:
    volumes:
       - static:/static
    env_file:
      - .env
    build:
      context: .
    ports:
    - "8000:8000"

  # django:
  #   image: bited:0.0.1
  #   build: .
  #   ports:
  #     - "8000:8000"

  nginx:
    build: ./nginx
    volumes:
      - static:/static
    ports:
      - "80:80"
    depends_on:
      - django_gunicorn

volumes:
  static:
